name: docktuna
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<4.0
  - pip
  - pip:
      - black>=25.1.0,<26.0.0
      - dotenv>=0.9.9,<1.0.0
      - isort>=6.0.1,<7.0.0
      - optuna>=4.2.1,<5.0.0
      - psycopg2>=2.9.10,<3.0.0
      - numpy>=2.1.3,<3.0.0
      - torch>=2.6.0,<3.0.0
      - torchvision>=0.21.0,<1.0.0
      - torchview>=0.2.6,<1.0.0
      - pytest>=8.3.5,<9.0.0
      - coverage>=7.6.12,<8.0.0
      - pytest-cov>=6.0.0,<7.0.0
