site_name: Docktuna Docs
repo_url: https://github.com/duanegoodner/docktuna
repo_name: duanegoodner/docktuna
theme:
  name: material

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]

markdown_extensions:
  - admonition
  - toc:
      permalink: true
